"""Topology-Guided Empirical Formula Discovery (TGEFD)."""

from .models import HypothesisParams, ModelResult
from .features import feature_library
from .sparse import SparseRegressor, TopoSparseRegressor, sparse_regression, topo_sparse_regression
from .api_v1 import (
    Artifacts,
    BudgetExceededError,
    ComputeBudget,
    Dataset,
    Decision,
    DiscoverRequest,
    DiscoverResponse,
    DiscoverSummary,
    ErrorStats,
    HypothesisSpace,
    ModelFamily,
    NoiseReportEntry,
    NoiseProfile,
    PersistenceImageConfig,
    PHConfig,
    Reproducibility,
    RepresentativeModel,
    TopologyConfig,
    TopologyEnergy,
    TopologyReport,
    discover,
    evaluate,
)
from .config import (
    AcceptanceConfig,
    AdaptiveConfig,
    ArtifactStoreConfig,
    ComputeBudgetConfig,
    DatasetConfig,
    DatasetLimitsConfig,
    DatasetX,
    DatasetY,
    EvaluationConfig,
    FeatureSpec,
    HypothesisSpaceConfig,
    NoiseConfig,
    OutputConfig,
    ParameterSpec,
    PersistentHomologyConfig,
    PIKernel,
    PIWeight,
    PersistenceImageConfig,
    RegularizationSpec,
    ReproducibilityConfig,
    RunConfig,
    StabilityScoreConfig,
    TGEFDConfig,
    TopologyConfig,
    ValidationError,
    config_to_request,
    load_config,
    parse_config,
)
from .artifacts import (
    ArtifactInfo,
    artifact_path,
    canonical_config_hash,
    canonical_config_yaml,
    verify_artifact,
    write_artifact_bundle,
)
from .storage import (
    ArtifactStoreConfig as StorageArtifactStoreConfig,
    GCSArtifactStore,
    LocalArtifactStore,
    S3ArtifactStore,
    build_store,
)
from .evaluation import METHOD_VERSION, AcceptancePolicy, EvaluationPolicy, StabilityScorePolicy
from .search import hypothesis_hypercube, search_models
from .adaptive import AdaptiveHypercubeConfig, adaptive_search_models
from .topology import (
    build_point_cloud,
    persistent_homology,
    persistent_components,
    significant_features,
    PersistenceComponent,
    PersistenceFeature,
    select_stable_models,
)
from .topo_regularization import (
    TopoPenaltyResult,
    hypothesis_cloud,
    perturb_coeffs,
    topological_penalty,
)
from .topo_vectors import (
    image_energy,
    landscape_norm,
    persistent_image,
    persistent_landscape,
)
from .data import make_demo_data, make_synthetic_truth_data

__all__ = [
    "HypothesisParams",
    "ModelResult",
    "feature_library",
    "SparseRegressor",
    "TopoSparseRegressor",
    "sparse_regression",
    "topo_sparse_regression",
    "Dataset",
    "HypothesisSpace",
    "PHConfig",
    "PersistenceImageConfig",
    "TopologyConfig",
    "NoiseProfile",
    "DiscoverRequest",
    "Decision",
    "ErrorStats",
    "RepresentativeModel",
    "ModelFamily",
    "NoiseReportEntry",
    "TopologyEnergy",
    "TopologyReport",
    "DiscoverSummary",
    "Artifacts",
    "BudgetExceededError",
    "ComputeBudget",
    "Reproducibility",
    "DiscoverResponse",
    "discover",
    "evaluate",
    "ValidationError",
    "RunConfig",
    "DatasetConfig",
    "DatasetLimitsConfig",
    "DatasetX",
    "DatasetY",
    "FeatureSpec",
    "ParameterSpec",
    "RegularizationSpec",
    "HypothesisSpaceConfig",
    "PersistentHomologyConfig",
    "PIWeight",
    "PIKernel",
    "PersistenceImageConfig",
    "TopologyConfig",
    "NoiseConfig",
    "AcceptanceConfig",
    "AdaptiveConfig",
    "ArtifactStoreConfig",
    "ComputeBudgetConfig",
    "StorageArtifactStoreConfig",
    "StabilityScoreConfig",
    "EvaluationConfig",
    "OutputConfig",
    "ReproducibilityConfig",
    "TGEFDConfig",
    "load_config",
    "parse_config",
    "config_to_request",
    "ArtifactInfo",
    "artifact_path",
    "canonical_config_hash",
    "canonical_config_yaml",
    "verify_artifact",
    "write_artifact_bundle",
    "build_store",
    "LocalArtifactStore",
    "S3ArtifactStore",
    "GCSArtifactStore",
    "AcceptancePolicy",
    "StabilityScorePolicy",
    "EvaluationPolicy",
    "METHOD_VERSION",
    "hypothesis_hypercube",
    "search_models",
    "AdaptiveHypercubeConfig",
    "adaptive_search_models",
    "build_point_cloud",
    "persistent_homology",
    "persistent_components",
    "significant_features",
    "PersistenceComponent",
    "PersistenceFeature",
    "select_stable_models",
    "TopoPenaltyResult",
    "hypothesis_cloud",
    "perturb_coeffs",
    "topological_penalty",
    "persistent_landscape",
    "landscape_norm",
    "persistent_image",
    "image_energy",
    "make_demo_data",
    "make_synthetic_truth_data",
]
